Add sync to deployer, comment out verification

diff --git a/.github/workflows/.deploy.yml b/.github/workflows/.deploy.yml
--- a/.github/workflows/.deploy.yml
+++ b/.github/workflows/.deploy.yml
@@ -95,7 +95,7 @@ jobs:
     timeout-minutes: ${{ inputs.timeout-minutes }}
     strategy:
       matrix:
-        name: [database, backend, fluentbit, frontend, oracle-api]
+        name: [database, backend, fluentbit, frontend, oracle-api, sync]
         include:
           - name: database
             file: database/openshift.deploy.yml
@@ -134,6 +134,13 @@ jobs:
               ${{ inputs.target == 'prod' && '-p SERVICE_NAME=dbq01.nrs.bcgov' || '' }}
             triggers: ('oracle-api/')
             verification_path: "actuator/health"
+          - name: sync
+            file: sync/openshift.deploy.yml
+            overwrite: true
+            parameters: -p ZONE=${{ inputs.target }} -p TAG=${{ inputs.tag }} ${{ inputs.parameters }}
+            # post_rollout: oc create job ${{ env.JOB_JOB }} --from=cronjob/${{ env.CRONJOB }}
+            triggers: ('sync/')
+
     steps:
       - uses: bcgov-nr/action-deployer-openshift@v2.3.0
         id: deploys
@@ -150,8 +157,45 @@ jobs:
             ${{ github.event_name == 'pull_request' && '-p MIN_REPLICAS=1' || '' }}
             ${{ github.event_name == 'pull_request' && '-p MAX_REPLICAS=2' || '' }}
             ${{ matrix.parameters }}
+          post_rollout: ${{ matrix.post_rollout }}
           triggers: ${{ matrix.triggers }}
           verification_path: ${{ matrix.verification_path }}
 
       - id: trigger
         run: echo "triggered=${{ steps.deploys.outputs.triggered }}" >> $GITHUB_OUTPUT
+
+  # verify:
+  #   name: Verify
+  #   if: inputs.verify == true
+  #   environment: ${{ inputs.environment }}
+  #   needs: [deploy]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     # Send triggers to diff action
+  #     - id: diff
+  #       uses: bcgov-nr/action-diff-triggers@v0.2.0
+  #       with:
+  #         triggers: ${{ inputs.triggers }}
+
+  #     - name: Verify
+  #       if: steps.diff.outputs.triggered == 'true'
+  #       run: |
+  #         # Check job logs
+
+  #         # Login
+  #         oc login --token=${{ secrets.oc_token }} --server=${{ vars.oc_server }}
+  #         oc project ${{ secrets.oc_namespace }} #Safeguard!
+
+  #         # Follow
+  #         oc wait --for=jsonpath='{.status.failed}'=4 job/${{ env.JOB_JOB }} --timeout=1m || true
+  #         oc logs -l job-name=${{ env.JOB_JOB }} --tail=50 --follow
+
+  #         # Results and exit code
+  #         oc get job ${{ env.JOB_JOB }}
+
+  #         if [ $(oc get job ${{ env.JOB_JOB }} -o jsonpath='{.status.ready}') -eq 0 ]; then
+  #           echo "Job successful!"
+  #         else
+  #           echo "Job failed!"
+  #           exit 1
+  #         fi
