Setup sync cronjob verification

diff --git a/.github/workflows/.deploy.yml b/.github/workflows/.deploy.yml
--- a/.github/workflows/.deploy.yml
+++ b/.github/workflows/.deploy.yml
@@ -35,6 +35,13 @@ on:
         required: false
         type: number
 
+      ### Not ready yet
+      verify:
+        description: Run the cronjob and verify results?  [true|false]
+        required: false
+        type: boolean
+        default: false
+
     outputs:
       triggered:
         description: 'Has a deployment has been triggered?'
@@ -162,38 +169,38 @@ jobs:
       - id: trigger
         run: echo "triggered=${{ steps.deploys.outputs.triggered }}" >> $GITHUB_OUTPUT
 
-  # verify:
-  #   name: Verify
-  #   if: inputs.verify == true
-  #   environment: ${{ inputs.environment }}
-  #   needs: [deploy]
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     # Send triggers to diff action
-  #     - id: diff
-  #       uses: bcgov-nr/action-diff-triggers@v0.2.0
-  #       with:
-  #         triggers: ${{ inputs.triggers }}
+  verify:
+    name: Verify
+    if: inputs.verify == true
+    environment: ${{ inputs.environment }}
+    needs: [deploy]
+    runs-on: ubuntu-latest
+    steps:
+      # Send triggers to diff action
+      - id: diff
+        uses: bcgov-nr/action-diff-triggers@v0.2.0
+        with:
+          triggers: ${{ inputs.triggers }}
 
-  #     - name: Verify
-  #       if: steps.diff.outputs.triggered == 'true'
-  #       run: |
-  #         # Check job logs
+      - name: Verify
+        if: steps.diff.outputs.triggered == 'true'
+        run: |
+          # Check job logs
 
-  #         # Login
-  #         oc login --token=${{ secrets.oc_token }} --server=${{ vars.oc_server }}
-  #         oc project ${{ secrets.oc_namespace }} #Safeguard!
+          # Login
+          oc login --token=${{ secrets.oc_token }} --server=${{ vars.oc_server }}
+          oc project ${{ secrets.oc_namespace }} #Safeguard!
 
-  #         # Follow
-  #         oc wait --for=jsonpath='{.status.failed}'=4 job/${{ env.JOB_JOB }} --timeout=1m || true
-  #         oc logs -l job-name=${{ env.JOB_JOB }} --tail=50 --follow
+          # Follow
+          oc wait --for=jsonpath='{.status.failed}'=4 job/${{ env.JOB_JOB }} --timeout=1m || true
+          oc logs -l job-name=${{ env.JOB_JOB }} --tail=50 --follow
 
-  #         # Results and exit code
-  #         oc get job ${{ env.JOB_JOB }}
+          # Results and exit code
+          oc get job ${{ env.JOB_JOB }}
 
-  #         if [ $(oc get job ${{ env.JOB_JOB }} -o jsonpath='{.status.ready}') -eq 0 ]; then
-  #           echo "Job successful!"
-  #         else
-  #           echo "Job failed!"
-  #           exit 1
-  #         fi
+          if [ $(oc get job ${{ env.JOB_JOB }} -o jsonpath='{.status.ready}') -eq 0 ]; then
+            echo "Job successful!"
+          else
+            echo "Job failed!"
+            exit 1
+          fi
