Catch missed files

diff --git a/.github/workflows/merge-main.yml b/.github/workflows/merge-main.yml
--- a/.github/workflows/merge-main.yml
+++ b/.github/workflows/merge-main.yml
@@ -5,24 +5,45 @@ on:
     branches:
       - main
     paths-ignore:
-      - ".github/ISSUE_TEMPLATE/*"
       - "**.md"
   workflow_dispatch:
+
+env:
+  REGISTRY: ghcr.io
+  NAME: nrbestapi
 
 concurrency:
   group: ${{ github.workflow }}
   cancel-in-progress: true
 
 jobs:
+  # https://github.com/marketplace/actions/ghcr-io-container-cleanup
+  cleanup-ghcr:
+    name: Cleanup Container Registry
+    runs-on: ubuntu-latest
+    steps:
+      - name: Delete old packages
+        uses: davahome/ghcr-cleanup@v1.1.0.1
+        with:
+          delete_untagged: 1
+          keep_versions: 10
+          keep_versions_untagged: 0
+          minimum_days: 14
+          owner: orgs/bcgov
+          package: ${{ github.event.repository.name }}
+          skip_tags: prod-service-api
+          token: ${{ secrets.GITHUB_TOKEN }}
+
   codeql:
     name: Semantic Code Analysis
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-latest
     permissions:
       actions: read
       contents: read
       security-events: write
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
       - name: Initialize
         uses: github/codeql-action/init@v2
@@ -31,7 +52,7 @@ jobs:
           languages: java
 
       - name: Set up JDK 17
-        uses: actions/setup-java@v3
+        uses: actions/setup-java@v2
         with:
           java-version: "17"
           distribution: "temurin"
@@ -50,42 +71,42 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
-      - uses: actions/cache@v3
+      - uses: actions/cache@v2
         with:
           path: |
             ~/.m2
-          key: ${{ runner.os }}-maven-test-${{ hashFiles('**/backend/pom.xml') }}
+          key: ${{ runner.os }}-maven-test-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
             ${{ runner.os }}-maven-test-
 
       - name: Cache SonarCloud packages
-        uses: actions/cache@v3
+        uses: actions/cache@v2
         with:
           path: ~/.sonar/cache
           key: ${{ runner.os }}-sonar
           restore-keys: ${{ runner.os }}-sonar
 
       - name: Set up JDK 17
-        uses: actions/setup-java@v3
+        uses: actions/setup-java@v2
         with:
           java-version: "17"
           distribution: "temurin"
 
       - name: Unit Tests
-        run: mvn --no-transfer-progress test --file backend/pom.xml
+        run: mvn --no-transfer-progress test --file pom.xml
 
       - name: Integration Tests
-        run: mvn --no-transfer-progress verify -P integration-test --file backend/pom.xml
+        run: mvn --no-transfer-progress verify -P integration-test --file pom.xml
 
       - name: Code Coverage
-        run: mvn --no-transfer-progress clean verify -P all-tests --file backend/pom.xml
+        run: mvn --no-transfer-progress clean verify -P all-tests --file pom.xml
 
       - name: Generate JaCoCo Badge
         uses: cicirello/jacoco-badge-generator@v2
         id: jacoco
         with:
           generate-branches-badge: true
-          jacoco-csv-file: backend/target/coverage-reports/merged-test-report/jacoco.csv
+          jacoco-csv-file: target/coverage-reports/merged-test-report/jacoco.csv
 
       - name: Log coverage percentage
         run: |
@@ -103,13 +124,13 @@ jobs:
           fi
 
       - name: Upload JaCoCo coverage report
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v2
         with:
           name: jacoco-report
-          path: backend/target/coverage-reports/merged-test-report/
+          path: target/coverage-reports/merged-test-report/
 
       - name: SonarCloud Scan
-        run: mvn --no-transfer-progress clean verify package -P all-tests sonar:sonar -Dsonar.projectKey=bcgov_nr-spar-backend -Dsonar.coverage.jacoco.xmlReportPaths=target/coverage-reports/merged-test-report/jacoco.xml --file backend/pom.xml
+        run: mvn --no-transfer-progress clean verify package -P all-tests sonar:sonar -Dsonar.projectKey=bcgov_nr-backend-starting-api -Dsonar.coverage.jacoco.xmlReportPaths=target/coverage-reports/merged-test-report/jacoco.xml --file pom.xml
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
@@ -126,11 +147,11 @@ jobs:
           token: ${{ secrets.PAT }}
           fetch-depth: 0
 
-      - uses: actions/cache@v3
+      - uses: actions/cache@v2
         with:
           path: |
             ~/.m2
-          key: ${{ runner.os }}-maven-test-${{ hashFiles('**/backend/pom.xml') }}
+          key: ${{ runner.os }}-maven-test-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
             ${{ runner.os }}-maven-test-
 
@@ -141,7 +162,6 @@ jobs:
           distribution: "temurin"
 
       - name: Conventional Changelog Update
-        continue-on-error: true
         uses: TriPSs/conventional-changelog-action@v3
         id: changelog
         with:
@@ -150,15 +170,14 @@ jobs:
           skip-version-file: "true"
           skip-commit: "true"
           git-push: "false"
-          skip-on-empty: "false"
 
       - name: Set new version
         run: |
           echo "::set-output name=version::${{ steps.changelog.outputs.version }}"
-          mvn versions:set -DnewVersion='${{ steps.changelog.outputs.version }}' -f backend/pom.xml -DskipTests -Dtests.skip=true -Dskip.unit.tests=true
+          mvn versions:set -DnewVersion='${{ steps.changelog.outputs.version }}' -f pom.xml -DskipTests -Dtests.skip=true -Dskip.unit.tests=true
 
       - name: Update POM
-        run: mvn versions:commit --file backend/pom.xml
+        run: mvn versions:commit
 
       - name: Commit pom and changelog
         uses: EndBug/add-and-commit@v9
@@ -166,12 +185,12 @@ jobs:
           author_name: Ci Bot
           author_email: cibot@users.noreply.github.com
           message: "doc: updating pom to ${{ steps.changelog.outputs.version }} [ci skip]"
-          add: '["backend/pom.xml","CHANGELOG.md"]'
+          add: '["pom.xml","CHANGELOG.md"]'
 
       - name: Create Release
         uses: actions/create-release@v1
         env:
-          GITHUB_TOKEN: ${{ secrets.PAT }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           tag_name: ${{ steps.changelog.outputs.tag }}
           release_name: ${{ steps.changelog.outputs.tag }}
@@ -180,38 +199,57 @@ jobs:
   deploy-test:
     name: TEST Deployment
     needs:
+      - cleanup-ghcr
       - codeql
       - sonarcloud
       - release
-    environment: test
-    runs-on: ubuntu-22.04
-    strategy:
-      matrix:
-        name: [init, database, backend]
-        include:
-          - name: init
-            file: common/openshift.init.yml
-            overwrite: false
-          - name: database
-            file: database/openshift.deploy.yml
-            overwrite: false
-          - name: backend
-            file: backend/openshift.deploy.yml
-            overwrite: true
-            parameters: -p MIN_REPLICAS=1 -p MAX_REPLICAS=2 -p BUILD=test-${{ needs.release.outputs.version }}
+    runs-on: ubuntu-latest
+    environment:
+      name: test
+    env:
+      ZONE: test
+      NRBESTAPI_VERSION: ${{ needs.release.outputs.version }}
     steps:
-      - uses: bcgov-nr/action-deployer-openshift@v1.0.2
+      - uses: actions/checkout@v3
+      - name: Print NRBESTAPI_VERSION env
+        run: echo NRBESTAPI_VERSION:test-${{ env.NRBESTAPI_VERSION }}
+      - name: Deploy
+        run: |
+          # Login to OpenShift and select project
+          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
+          oc project ${{ secrets.OC_NAMESPACE }}
+          # Do not replace database; 'oc create' kicks up an error if objects already exist
+          #oc process -f .github/openshift/deploy.database.yml -p ZONE=${{ env.ZONE }} | oc create -f - || true
+          # Process and apply deployment templates
+          oc process -f .github/openshift/deploy.backend.yml -p ZONE=${{ env.ZONE }} \
+            -p NRBESTAPI_VERSION=test-${{ env.NRBESTAPI_VERSION }} \
+            -p ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }} \
+            -p PROMOTE=${{ github.repository }}:${{ env.ZONE }}-service-api | oc apply -f -
+          # Follow any active rollouts (see deploymentconfigs)
+          #oc rollout status dc/${{ env.NAME }}-${{ env.ZONE }}-database -w
+          oc rollout status dc/${{ env.NAME }}-${{ env.ZONE }}-service-api -w
+          # Remove completed build runs, build pods and deployment pods
+          for p in $(oc get po | grep "Completed" | awk '{print $1}')
+          do
+            oc delete po ${p}
+          done
+
+  zap-service-api:
+    name: Service API Pen Tests
+    needs:
+      - deploy-test
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: ZAP Scan
+        uses: zaproxy/action-full-scan@v0.3.0
         with:
-          file: ${{ matrix.file }}
-          oc_namespace: ${{ vars.OC_NAMESPACE }}
-          oc_server: ${{ vars.OC_SERVER }}
-          oc_token: ${{ secrets.OC_TOKEN }}
-          overwrite: ${{ matrix.overwrite }}
-          penetration_test: false
-          verification_path: "actuator/health"
-          parameters: -p ZONE=test -p NAME=${{ github.event.repository.name }}
-            -p PROMOTE=${{ github.repository }}/${{ matrix.name }}:test
-            ${{ matrix.parameters }}
+          target: https://${{ env.NAME }}-test-service-api.apps.silver.devops.gov.bc.ca/
+          cmd_options: "-a"
+          allow_issue_writing: false
+          fail_action: false
 
   api-tests:
     name: Newman API tests runner
@@ -237,65 +275,161 @@ jobs:
 
       - name: Run Postman Collection
         run: |
-          newman run test/postman/starting-api.postman_collection.json -e test/postman/starting-api.postman_environment.json \
-            --env-var "releaseVer=test=${{ env.NR_SPAR_BACKEND_VERSION }}" \
-            --env-var "authServer=${{ secrets.KEYCLOAK_SERVER_REALM }}" \
-            --env-var "authClient=${{ secrets.KC_SERVICE_ACCOUNT_NAME }}" \
-            --env-var "authClient=${{ secrets.KC_SERVICE_ACCOUNT_PASS }}" \
-            --suppress-exit-code -r htmlextra --reporter-htmlextra-export testArtifacts/api-tests-report.html
+          newman run test/postman/starting-api.postman_collection.json -e test/postman/starting-api.postman_environment.json --suppress-exit-code -r htmlextra --reporter-htmlextra-export testArtifacts/api-tests-report.html
 
       - name: Output the results
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v2
         with:
-          name: API test report
+          name: Reports
           path: testArtifacts
+
+  # https://github.com/snyk/cli, https://github.com/snyk/actions
+  # Note: using free tier - called late in pipeline to limit runs
+  # Disabled snyk because it don't support Java 17 or Maven with JDK 17 yet
+
+  # https://github.com/marketplace/actions/aqua-security-trivy
+  trivy-repo:
+    name: Repository Report
+    needs:
+      - zap-service-api
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Run Trivy vulnerability scanner in repo mode
+        uses: aquasecurity/trivy-action@0.3.0
+        with:
+          scan-type: "fs"
+          format: "sarif"
+          output: "trivy-results.sarif"
+          ignore-unfixed: true
+          severity: "CRITICAL,HIGH"
+          security-checks: "vuln,secret,config"
+
+      - name: Upload Trivy scan results to GitHub Security tab
+        uses: github/codeql-action/upload-sarif@v2
+        with:
+          sarif_file: "trivy-results.sarif"
+
+  image-service-api:
+    name: Service API Image Handling
+    needs:
+      - zap-service-api
+    outputs:
+      build: ${{ steps.check.outputs.build }}
+    env:
+      COMPONENT: service-api
+      PREV: test
+      ZONE: prod
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check for image changes
+        id: check
+        run: |
+          # Vars
+          IMG_PREV="${{ env.REGISTRY }}/${{ github.repository }}:${{ env.PREV }}-${{ env.COMPONENT }}"
+          IMG_ZONE="${{ env.REGISTRY }}/${{ github.repository }}:${{ env.ZONE }}-${{ env.COMPONENT }}"
+          # Pull previous image; grab SHA
+          docker pull "${IMG_PREV}"
+          SHA_PREV=$(docker inspect -f '{{.Id}}' "${IMG_PREV}")
+          # Use blank SHA for promoted image, unless a real one exists instead
+          docker pull "${IMG_ZONE}" && \
+            SHA_ZONE=$(docker inspect -f '{{.Id}}' "${IMG_ZONE}") ||
+            SHA_ZONE=""
+          # Output SHAs
+          echo -e "\n${IMG_PREV}: ${SHA_PREV}"
+          echo -e "${IMG_ZONE}: ${SHA_ZONE}\n"
+          # If different, then trigger updates
+          if [[ "${SHA_PREV}" != "${SHA_ZONE}" ]]; then
+            echo "::set-output name=build::true"
+            echo "Image has changed"
+            exit 0
+          fi
+          echo "Image promotion not required"
+      - name: Promote Service API Image
+        if: steps.check.outputs.build == 'true'
+        uses: shrink/actions-docker-registry-tag@v2
+        with:
+          registry: ${{ env.REGISTRY }}
+          repository: ${{ github.repository }}
+          target: ${{ env.PREV }}-${{ env.COMPONENT }}
+          tags: |
+            ${{ env.ZONE }}-${{ env.COMPONENT }}
 
   deploy-prod:
     name: PROD Deployment
     needs:
-      - api-tests
-    environment: prod
-    runs-on: ubuntu-22.04
-    strategy:
-      matrix:
-        name: [init, database, backend]
-        include:
-          - name: init
-            file: common/openshift.init.yml
-            overwrite: false
-          - name: database
-            file: database/openshift.deploy.yml
-            overwrite: false
-          - name: backend
-            file: backend/openshift.deploy.yml
-            overwrite: true
-            parameters: -p BUILD=prod-${{ needs.release.outputs.version }}
+      - image-service-api
+      - trivy-repo
+      - release
+    runs-on: ubuntu-latest
+    environment:
+      name: prod
+    env:
+      ZONE: prod
+      PREV: test
+      NRBESTAPI_VERSION: ${{ needs.release.outputs.version }}
     steps:
-      - uses: bcgov-nr/action-deployer-openshift@v1.0.2
-        with:
-          file: ${{ matrix.file }}
-          oc_namespace: ${{ vars.OC_NAMESPACE }}
-          oc_server: ${{ vars.OC_SERVER }}
-          oc_token: ${{ secrets.OC_TOKEN }}
-          overwrite: ${{ matrix.overwrite }}
-          penetration_test: false
-          verification_path: "actuator/health"
-          parameters: -p ZONE=prod -p NAME=${{ github.event.repository.name }}
-            -p PROMOTE=${{ github.repository }}/${{ matrix.name }}:test
-            ${{ matrix.parameters }}
+      - name: Remove any stale images
+        if: needs.image-service-api.outputs.build == 'true'
+        env:
+          COMPONENT: service-api
+        run: |
+          # Login to OpenShift and select project
+          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
+          oc project ${{ secrets.OC_NAMESPACE }}
+          oc delete is/${{ env.NAME }}-${{ env.ZONE}}-${{ env.COMPONENT }} || true
 
-  image-promotions:
-    name: Promote Images to PROD
-    needs:
-      - deploy-prod
-    runs-on: ubuntu-22.04
-    strategy:
-      matrix:
-        component: [backend, database]
-    steps:
-      - uses: shrink/actions-docker-registry-tag@v3
+      - uses: actions/checkout@v3
+      - name: Print NRBESTAPI_VERSION env
+        run: echo NRBESTAPI_VERSION:prod-${{ env.NRBESTAPI_VERSION }}
+      - name: Deploy
+        run: |
+          # Login to OpenShift and select project
+          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
+          oc project ${{ secrets.OC_NAMESPACE }}
+
+          # Clear stale images for import/replacement
+          if [ $(oc get is -l app=${{ env.NAME }}-${{ env.ZONE }} -o name | grep -v database | wc -l) -gt 0 ]; then
+            oc delete is -l app=${{ env.NAME }}-${{ env.ZONE }}
+          fi
+
+          # Process and apply deployment templates
+          #oc process -f .github/openshift/deploy.database.yml -p ZONE=${{ env.ZONE }} | oc apply -f -
+          oc process -f .github/openshift/deploy.backend.yml -p ZONE=${{ env.ZONE }} \
+            -p NRBESTAPI_VERSION=prod-${{ env.NRBESTAPI_VERSION }} \
+            -p ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }} \
+            -p PROMOTE=${{ github.repository }}:${{ env.PREV }}-service-api | oc apply -f -
+
+          # Follow any active rollouts (see deploymentconfigs)
+          #oc rollout status dc/${{ env.NAME }}-${{ env.ZONE }}-database -w
+          oc rollout status dc/${{ env.NAME }}-${{ env.ZONE }}-service-api -w
+
+          # Remove completed build runs, build pods and deployment pods
+          for p in $(oc get po | grep "Completed" | awk '{print $1}')
+          do
+            oc delete po ${p}
+          done
+
+      - name: Promote Image to PROD
+        uses: shrink/actions-docker-registry-tag@v2
         with:
-          registry: ghcr.io
-          repository: ${{ github.repository }}/${{ matrix.component }}
-          target: test
-          tags: prod
+          registry: ${{ env.REGISTRY }}
+          repository: ${{ github.repository }}
+          target: ${{ env.PREV }}-service-api
+          tags: |
+            prod-service-api
+
+# # Uncomment to for development and troubleshooting
+# # https://docs.github.com/en/actions/learn-github-actions/contexts
+# view-context:
+#   name: View GitHub Context
+#   runs-on: ubuntu-latest
+#   steps:
+#     - name: Echo GitHub context
+#       uses: satackey/action-js-inline@v0.0.2
+#       with:
+#         script: |
+#           const github = require('@actions/github');
+#           console.log(JSON.stringify(github, null, 2));
