Test

diff --git a/.github/workflows/pr-open.yml b/.github/workflows/pr-open.yml
--- a/.github/workflows/pr-open.yml
+++ b/.github/workflows/pr-open.yml
@@ -11,28 +11,28 @@ concurrency:
 permissions: {}
 
 jobs:
-  builds:
-    name: Builds
-    runs-on: ubuntu-24.04
-    outputs:
-      triggered: ${{ steps.build.outputs.triggered }}
-    permissions:
-      packages: write
-    strategy:
-      matrix:
-        package: [backend, frontend, oracle-api]
-    steps:
-      - uses: bcgov/action-builder-ghcr@v2.3.0
-        id: build
-        with:
-          package: ${{ matrix.package }}
-          tag: ${{ github.event.number }}
-          tag_fallback: latest
-          triggers: ('${{ matrix.package }}/')
+  # builds:
+  #   name: Builds
+  #   runs-on: ubuntu-24.04
+  #   outputs:
+  #     triggered: ${{ steps.build.outputs.triggered }}
+  #   permissions:
+  #     packages: write
+  #   strategy:
+  #     matrix:
+  #       package: [backend, frontend, oracle-api]
+  #   steps:
+  #     - uses: bcgov/action-builder-ghcr@v2.3.0
+  #       id: build
+  #       with:
+  #         package: ${{ matrix.package }}
+  #         tag: ${{ github.event.number }}
+  #         tag_fallback: latest
+  #         triggers: ('${{ matrix.package }}/')
 
   deploys:
     name: Deploys (${{ github.event.number }})
-    needs: [builds]
+    # needs: [builds]
     secrets: inherit
     uses: ./.github/workflows/.deploy.yml
     with:
@@ -49,19 +49,19 @@ jobs:
     secrets: inherit
     uses: ./.github/workflows/.tests.yml
 
-  results:
-    name: PR Results
-    if: always()
-    # Include all needs that could have failures!
-    needs: [builds, deploys, tests]
-    runs-on: ubuntu-24.04
-    steps:
-      - run: |
-          # View results
-          echo "needs.*.result: ${{ toJson(needs.*.result) }}"
+  # results:
+  #   name: PR Results
+  #   if: always()
+  #   # Include all needs that could have failures!
+  #   needs: [builds, deploys, tests]
+  #   runs-on: ubuntu-24.04
+  #   steps:
+  #     - run: |
+  #         # View results
+  #         echo "needs.*.result: ${{ toJson(needs.*.result) }}"
 
-      - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
-        run: |
-          # Job failure found
-          echo "At least one job has failed"
-          exit 1
+  #     - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
+  #       run: |
+  #         # Job failure found
+  #         echo "At least one job has failed"
+  #         exit 1
