feat(ci): get job results (#29)

diff --git a/.github/workflows/pr-open.yml b/.github/workflows/pr-open.yml
--- a/.github/workflows/pr-open.yml
+++ b/.github/workflows/pr-open.yml
@@ -9,13 +9,15 @@ concurrency:
   cancel-in-progress: true
 
 env:
-  JOB: ${{ github.event.repository.name }}-${{ github.event.number }}-sync
+  CRONJOB: ${{ github.event.repository.name }}-${{ github.event.number }}-sync
 
 jobs:
   # https://github.com/bcgov-nr/action-builder-ghcr
   builds:
     name: Builds
     runs-on: ubuntu-22.04
+    outputs:
+      digest: ${{ steps.builds.outputs.digest }}
     permissions:
       packages: write
     timeout-minutes: 10
@@ -32,6 +34,7 @@ jobs:
   deploys:
     name: Deploys
     needs: [builds]
+    if: needs.builds.outputs.digest != ''
     runs-on: ubuntu-latest
     steps:
       - name: Deploys
@@ -45,26 +48,50 @@ jobs:
           overwrite: true
           parameters: -p ZONE=${{ github.event.number }} -p TAG=${{ github.event.number }}
           post_rollout: 
-            oc create job ${{ env.JOB }}-${{ github.run_number }} --from=cronjob/${{ env.JOB }} &&
-            oc get job ${{ env.JOB }}-${{ github.run_number }}
-          triggers: ('sync/')
+            oc create job ${{ env.CRONJOB }}-${{ github.run_number }} --from=cronjob/${{ env.CRONJOB }} &&
+            oc get job ${{ env.CRONJOB }}-${{ github.run_number }}
 
   logs:
     name: Logs
     needs: [deploys]
     runs-on: ubuntu-latest
     steps:
+      - name: Override OpenShift version
+        env:
+          OC: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.13/openshift-client-linux.tar.gz
+        working-directory: /usr/local/bin/
+        run: |
+          # Override OpenShift version
+          curl --silent ${{ env.OC }} | tar -xzvf - oc
+          oc version
+
       - name: Logs
         run: |
           # Check job logs
 
-          # Login
+          # Login$
           oc login --token=${{ secrets.oc_token }} --server=${{ vars.oc_server }}
           oc project ${{ secrets.oc_namespace }} #Safeguard!
 
           # Follow
-          sleep 10
-          oc logs -l job-name=${{ env.JOB }}-${{ github.run_number }} --tail=50 --follow
+          oc create job ${{ env.CRONJOB }}-${{ github.run_number }} --from=cronjob/${{ env.CRONJOB }}
+          sleep 15
+          oc logs -l job-name=${{ env.CRONJOB }}-${{ github.run_number }} --tail=50 --follow
+
+          # Results and exit code
+          oc get job ${{ env.CRONJOB }}-${{ github.run_number }}
+
+          READY=$(oc get job ${{ env.CRONJOB }}-${{ github.run_number }} -o jsonpath='{.status.ready}')
+          echo "READY: $READY"
+
+          if [ $(oc get job ${{ env.CRONJOB }}-${{ github.run_number }} -o jsonpath='{.status.ready}') -eq 0 ]; then
+          if [ "${READY}" -eq 0 ]; then
+            echo "Job failed!"
+            exit 1
+          else
+            echo "Job successful!"
+            exit 0
+          fi
 
   results:
     name: PR Results
