Restore workflows

diff --git a/.github/workflows/pr-open.yml b/.github/workflows/pr-open.yml
--- a/.github/workflows/pr-open.yml
+++ b/.github/workflows/pr-open.yml
@@ -9,28 +9,28 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  # builds:
-  #   name: Builds
-  #   runs-on: ubuntu-22.04
-  #   outputs:
-  #     triggered: ${{ steps.build.outputs.triggered }}
-  #   permissions:
-  #     packages: write
-  #   strategy:
-  #     matrix:
-  #       package: [database, backend, frontend, oracle-api, sync]
-  #   steps:
-  #     - uses: bcgov-nr/action-builder-ghcr@v2.2.0
-  #       id: build
-  #       with:
-  #         package: ${{ matrix.package }}
-  #         tag: ${{ github.event.number }}
-  #         tag_fallback: latest
-  #         triggers: ('${{ matrix.package }}/')
+  builds:
+    name: Builds
+    runs-on: ubuntu-22.04
+    outputs:
+      triggered: ${{ steps.build.outputs.triggered }}
+    permissions:
+      packages: write
+    strategy:
+      matrix:
+        package: [database, backend, frontend, oracle-api, sync]
+    steps:
+      - uses: bcgov-nr/action-builder-ghcr@v2.2.0
+        id: build
+        with:
+          package: ${{ matrix.package }}
+          tag: ${{ github.event.number }}
+          tag_fallback: latest
+          triggers: ('${{ matrix.package }}/')
 
   deploys:
     name: Deploys
-    # needs: [builds]
+    needs: [builds]
     secrets: inherit
     uses: ./.github/workflows/.deploy.yml
 
@@ -41,19 +41,19 @@ jobs:
     secrets: inherit
     uses: ./.github/workflows/.tests.yml
 
-  # results:
-  #   name: PR Results
-  #   if: always()
-  #   # Include all needs that could have failures!
-  #   needs: [builds, deploys, tests]
-  #   runs-on: ubuntu-22.04
-  #   steps:
-  #     - run: |
-  #         # View results
-  #         echo "needs.*.result: ${{ toJson(needs.*.result) }}"
+  results:
+    name: PR Results
+    if: always()
+    # Include all needs that could have failures!
+    needs: [builds, deploys, tests]
+    runs-on: ubuntu-22.04
+    steps:
+      - run: |
+          # View results
+          echo "needs.*.result: ${{ toJson(needs.*.result) }}"
 
-  #     - if: contains(needs.*.result, 'failure')
-  #       run: |
-  #         # Job failure found
-  #         echo "At least one job has failed"
-  #         exit 1
+      - if: contains(needs.*.result, 'failure')
+        run: |
+          # Job failure found
+          echo "At least one job has failed"
+          exit 1
