Revert "fix(ci): improve results jobs/blocks (#1118)"
This reverts commit de77fa02aa9d7a1aeb5d436f84391f128a9e3dd0.

diff --git a/.github/workflows/pr-validate.yml b/.github/workflows/pr-validate.yml
--- a/.github/workflows/pr-validate.yml
+++ b/.github/workflows/pr-validate.yml
@@ -31,8 +31,16 @@ jobs:
 
   results:
     name: Validate Results
-    if: always() && (!failure()) && (!cancelled())
+    if: always()
     needs: [validate]
     runs-on: ubuntu-22.04
     steps:
-      - run: echo "Success!"
+      - run: |
+          # View results
+          echo "needs.*.result: ${{ toJson(needs.*.result) }}"
+
+      - if: contains(needs.*.result, 'failure')
+        run: |
+          # Job failure found
+          echo "At least one job has failed"
+          exit 1
